apiVersion: v1
kind: Service
metadata:
  name: "booking-service"
  labels:
    app: "booking-service"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8181
  selector:
    app: "booking-app"

#   sessionAffinity: ClientIP
#   sessionAffinityConfig:
#     clientIP:
#       timeoutSeconds: 10800
#   loadBalancerIP: ""
#   externalTrafficPolicy: Local
#   externalIPs:
#     - 192.50.51.208
#     - 10.0.0.1
#   clusterIP: 10.0.0.1
