apiVersion: v1
kind: Pod
metadata:
  name: "booking-pod"
  namespace: "guru-namespace"
  labels:
    app: "guru-booking"
spec:
  containers:
  - image: guru/booking:1.0
    name: guru-booking-container
    ports:
    - name: "http"
      containerPort: 8082
    imagePullPolicy: Never
    ## REsource limit ###
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    ## REsource limit ###
    livenessProbe:
      httpGet:
        path: "/bookTicket"
        port: 8181
      initialDelaySeconds: 100
      periodSeconds: 40
      failureThreshold: 4
      successThreshold: 1
      timeoutSeconds: 4
    readinessProbe:
      httpGet:
        path: "/bookTicket"
        port: 8181
      failureThreshold: 3
      initialDelaySeconds: 80
      timeoutSeconds: 3
      periodSeconds: 30
      successThreshold: 1