apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: booking
build:
  artifacts:
  - image: guru/booking
    context: .
    docker: {}
deploy:
  kubectl:
    manifests:
    - k8s/guru-namespace.yml
    - k8s/booking-config-map.yml
    - k8s/booking-deployment.yml
    - k8s/booking-services.yml
#    - k8s/booking-deployment-configmap.yml
#    - k8s/booking-pod.yml
